### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/JulioCezar-PayCheck#2]
It was not possible to use the application due the [syntax error](https://github.com/univas-first-exam/JulioCezar-PayCheck/blob/master/asset/js/SALARYController.js#L17-L20).

![image](https://cloud.githubusercontent.com/assets/5324414/10762222/436a30f8-7cac-11e5-97d4-83b81b65b811.png)

**Comment by juliocezah** [comment]
Syntax error has corrected.
