### ISSUE TITLE
Layout improvement

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/JulioCezar-PayCheck#4]
I'd like to suggest you to improve this layout to reflect what was asked in the exam.

![image](https://cloud.githubusercontent.com/assets/5324414/10762424/264bb9f0-7cad-11e5-92e0-32b3afb72e8b.png)

![image](https://cloud.githubusercontent.com/assets/5324414/10762434/2f2d5740-7cad-11e5-8e6c-ed70599e13b0.png)

**Comment by juliocezah** [comment]
Layout has changed as requested.
